FROM python:3.9

# Install supervisor
RUN apt-get update && apt-get install -y supervisor

RUN mkdir app

RUN cd app

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ARG DATABASE_URI
ENV DATABASE_URI=${DATABASE_URI}

ARG SECRET_KEY
ENV SECRET_KEY=${SECRET_KEY}

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ARG STABILITY_API_KEY
ENV STABILITY_API_KEY=${STABILITY_API_KEY}

ARG SPACE_REGION
ENV SPACE_REGION=${SPACE_REGION}

ARG SPACE_NAME
ENV SPACE_NAME=${SPACE_NAME}

ARG SPACE_KEY
ENV SPACE_KEY=${SPACE_KEY}

ARG SPACE_SECRET
ENV SPACE_SECRET=${SPACE_SECRET}

ARG SPACE_ENDPOINT
ENV SPACE_EDGE_ENDPOINT=${SPACE_EDGE_ENDPOINT}

RUN flask db upgrade

RUN python manage.py


EXPOSE 80

CMD bash -c "supervisord -c supervisord.conf"