"""empty message

Revision ID: 329d3271ba1d
Revises: 7dafc2c6104b
Create Date: 2023-04-24 09:50:35.107052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329d3271ba1d'
down_revision = '7dafc2c6104b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('email')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
