"""empty message

Revision ID: 73479c094dec
Revises: 329d3271ba1d
Create Date: 2023-04-24 10:15:15.175858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73479c094dec'
down_revision = '329d3271ba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
